---
fixtures:
  symlinks:
    profile: site/profile
    role: site/role
  repositories:
    node_manager:
      repo: https://github.com/puppetlabs/prosvcs-node_manager.git
      ref: master
    app_update:
      repo: https://github.com/beergeek/beergeek-app_update.git
      ref: yum_demo
    ssh:
      repo: https://github.com/beergeek/puppet-ssh.git
      ref: master
  forge_modules:
    windows_env:
      repo: badgerious-windows_env
      ref: 2.2.2
    windows_path:
      repo: basti1302-windows_path
      ref: 0.1.1
    chocolatey:
      repo: chocolatey-chocolatey
      ref: 1.2.2
    make:
      repo: croddy-make
      ref: 0.0.5
    puppetdbquery:
      repo: dalen-puppetdbquery
      ref: 2.1.1
    sysctl:
      repo: fiddyspence-sysctl
      ref: 1.1.0
    portage:
      repo: gentoo-portage
      ref: 2.3.0
    download_file:
      repo: puppet-download_file
      ref: 1.3.0
    iis:
      repo: puppet-iis
      ref: 2.0.2
    windowsfeature:
      repo: puppet-windowsfeature
      ref: 1.1.0
    acl:
      repo: puppetlabs-acl
      ref: 1.1.2
    apache:
      repo: puppetlabs-apache
      ref: 1.5.0
    concat:
      repo: puppetlabs-concat
      ref: 1.2.3
    dsc:
      repo: puppetlabs-dsc
      ref: 0.8.1
    firewall:
      repo: puppetlabs-firewall
      ref: 1.7.0
    gcc:
      repo: puppetlabs-gcc
      ref: 0.3.0
    git:
      repo: puppetlabs-git
      ref: 0.4.0
    haproxy:
      repo: puppetlabs-haproxy
      ref: 1.2.0
    inifile:
      repo: puppetlabs-inifile
      ref: 1.4.0
    mysql:
      repo: puppetlabs-mysql
      ref: 3.4.0
    ntp:
      repo: puppetlabs-ntp
      ref: 4.0.0
    pe_gem:
      repo: puppetlabs-pe_gem
      ref: 0.1.1
    powershell:
      repo: puppetlabs-powershell
      ref: 1.0.6
    puppetserver_gem:
      repo: puppetlabs-puppetserver_gem
      ref: 0.1.0
    reboot:
      repo: puppetlabs-reboot
      ref: 1.2.1
    registry:
      repo: puppetlabs-registry
      ref: 1.1.3
    ruby:
      repo: puppetlabs-ruby
      ref: 0.4.0
    stdlib:
      repo: puppetlabs-stdlib
      ref: 4.9.0
    tomcat:
      repo: puppetlabs-tomcat
      ref: 1.5.0
    vcsrepo:
      repo: puppetlabs-vcsrepo
      ref: 1.3.0
    wsus_client:
      repo: puppetlabs-wsus_client
      ref: 1.0.1
    puppet_certificate:
      repo: reidmv-puppet_certificate
      ref: 0.0.3
    logrotate:
      repo: rodjek-logrotate
      ref: 1.1.1
    resolv_conf:
      repo: saz-resolv_conf
      ref: 3.0.5
    rsyslog:
      repo: saz-rsyslog
      ref: 3.5.1
    sudo:
      repo: saz-sudo
      ref: 3.1.0
    timezone:
      repo: saz-timezone
      ref: 3.3.0
    epel:
      repo: stahnma-epel
      ref: 1.2.2
    r10k:
      repo: zack-r10k
      ref: 3.2.0
    noop:
      repo: trlinkin-noop
      ref: 0.0.2
